// Comprehensive list of Pokémon names for BossSearch autocomplete.
// Covers all Gen 1–2 (251), key Gen 3–9 legendaries, starters,
// popular species, and Mega/Primal/regional forms.
export const ALL_POKEMON: string[] = [
  // === Gen 1 (151) ===
  'Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon', 'Charizard',
  'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Butterfree',
  'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot',
  'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok',
  'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran♀', 'Nidorina',
  'Nidoqueen', 'Nidoran♂', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable',
  'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
  'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
  'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
  'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwag',
  'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop',
  'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
  'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
  'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', 'Farfetch\'d', 'Doduo',
  'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk', 'Shellder',
  'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee',
  'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
  'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung',
  'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey', 'Tangela',
  'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu',
  'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz', 'Magmar',
  'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras', 'Ditto',
  'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte',
  'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno',
  'Zapdos', 'Moltres', 'Dratini', 'Dragonair', 'Dragonite', 'Mewtwo', 'Mew',

  // === Gen 2 (100) ===
  'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava', 'Typhlosion',
  'Totodile', 'Croconaw', 'Feraligatr', 'Sentret', 'Furret', 'Hoothoot',
  'Noctowl', 'Ledyba', 'Ledian', 'Spinarak', 'Ariados', 'Crobat',
  'Chinchou', 'Lanturn', 'Pichu', 'Cleffa', 'Igglybuff', 'Togepi',
  'Togetic', 'Natu', 'Xatu', 'Mareep', 'Flaaffy', 'Ampharos',
  'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip',
  'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora', 'Yanma',
  'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow', 'Slowking',
  'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco', 'Forretress',
  'Dunsparce', 'Gligar', 'Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
  'Scizor', 'Shuckle', 'Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
  'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
  'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour', 'Houndoom',
  'Kingdra', 'Phanpy', 'Donphan', 'Porygon2', 'Stantler', 'Smeargle',
  'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank',
  'Blissey', 'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar',
  'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi',

  // === Gen 3 (key Pokémon) ===
  'Treecko', 'Grovyle', 'Sceptile', 'Torchic', 'Combusken', 'Blaziken',
  'Mudkip', 'Marshtomp', 'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon',
  'Linoone', 'Beautifly', 'Dustox', 'Lotad', 'Seedot', 'Taillow',
  'Ralts', 'Kirlia', 'Gardevoir', 'Breloom', 'Slakoth', 'Slaking',
  'Makuhita', 'Hariyama', 'Nosepass', 'Skitty', 'Sableye', 'Mawile',
  'Aron', 'Lairon', 'Aggron', 'Meditite', 'Medicham', 'Plusle', 'Minun',
  'Roselia', 'Wailmer', 'Wailord', 'Numel', 'Camerupt', 'Torkoal',
  'Flygon', 'Cacnea', 'Cacturne', 'Zangoose', 'Seviper', 'Lunatone',
  'Solrock', 'Corphish', 'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep',
  'Cradily', 'Anorith', 'Armaldo', 'Milotic', 'Castform', 'Kecleon',
  'Shuppet', 'Banette', 'Duskull', 'Dusclops', 'Tropius', 'Chimecho',
  'Absol', 'Snorunt', 'Glalie', 'Spheal', 'Sealeo', 'Walrein',
  'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
  'Shelgon', 'Salamence', 'Beldum', 'Metang', 'Metagross',
  'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios',
  'Kyogre', 'Groudon', 'Rayquaza', 'Jirachi', 'Deoxys',

  // === Gen 4 (key Pokémon) ===
  'Turtwig', 'Grotle', 'Torterra', 'Chimchar', 'Monferno', 'Infernape',
  'Piplup', 'Prinplup', 'Empoleon', 'Staraptor', 'Roserade', 'Cranidos',
  'Rampardos', 'Shieldon', 'Bastiodon', 'Lucario', 'Hippopotas', 'Hippowdon',
  'Toxicroak', 'Garchomp', 'Riolu', 'Leafeon', 'Glaceon',
  'Gliscor', 'Mamoswine', 'Porygon-Z', 'Gallade', 'Probopass', 'Dusknoir',
  'Froslass', 'Rotom', 'Uxie', 'Mesprit', 'Azelf',
  'Dialga', 'Palkia', 'Heatran', 'Regigigas', 'Giratina',
  'Cresselia', 'Manaphy', 'Darkrai', 'Shaymin', 'Arceus',
  'Giratina (Ændret form)', 'Giratina (Oprindelse form)',

  // === Gen 5 (key Pokémon) ===
  'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite', 'Emboar',
  'Oshawott', 'Dewott', 'Samurott', 'Lillipup', 'Herdier', 'Stoutland',
  'Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Seismitoad', 'Throh', 'Sawk',
  'Basculin', 'Darmanitan', 'Scraggy', 'Scrafty', 'Sigilyph',
  'Cofagrigus', 'Carracosta', 'Archeops', 'Garbodor', 'Zoroark',
  'Cinccino', 'Gothitelle', 'Reuniclus', 'Swanna', 'Vanilluxe',
  'Emolga', 'Karrablast', 'Escavalier', 'Ferrothorn', 'Klinklang',
  'Eelektross', 'Haxorus', 'Beartic', 'Cryogonal', 'Accelgor',
  'Stunfisk', 'Mienshao', 'Druddigon', 'Golurk', 'Bisharp',
  'Bouffalant', 'Braviary', 'Mandibuzz', 'Hydreigon', 'Volcarona',
  'Cobalion', 'Terrakion', 'Virizion', 'Tornadus', 'Thundurus',
  'Reshiram', 'Zekrom', 'Landorus', 'Kyurem', 'Keldeo', 'Genesect',

  // === Gen 6 (key Pokémon) ===
  'Chesnaught', 'Delphox', 'Greninja', 'Diggersby', 'Talonflame',
  'Vivillon', 'Aromatisse', 'Slurpuff', 'Malamar', 'Clawitzer',
  'Goodra', 'Aurorus', 'Tyrantrum', 'Sylveon',
  'Hawlucha', 'Dedenne', 'Carbink', 'Goomy', 'Klefki', 'Phantump',
  'Trevenant', 'Bergmite', 'Avalugg', 'Noivern',
  'Xerneas', 'Yveltal', 'Zygarde', 'Diancie', 'Hoopa', 'Volcanion',

  // === Gen 7 (key Pokémon) ===
  'Decidueye', 'Incineroar', 'Primarina', 'Lycanroc',
  'Wishiwashi', 'Toxapex', 'Mudbray', 'Mudsdale', 'Araquanid',
  'Comfey', 'Passimian', 'Golisopod', 'Palossand', 'Pyukumuku',
  'Type: Null', 'Silvally', 'Kommo-o', 'Tapu Koko', 'Tapu Lele',
  'Tapu Bulu', 'Tapu Fini', 'Solgaleo', 'Lunala',
  'Nihilego', 'Buzzwole', 'Pheromosa', 'Xurkitree', 'Celesteela',
  'Kartana', 'Guzzlord', 'Necrozma', 'Magearna', 'Marshadow',
  'Poipole', 'Naganadel', 'Stakataka', 'Blacephalon', 'Zeraora',

  // === Gen 8 (key Pokémon) ===
  'Rillaboom', 'Cinderace', 'Inteleon',
  'Corviknight', 'Drednaw', 'Alcremie', 'Falinks',
  'Pincurchin', 'Frosmoth', 'Stonjourner', 'Eiscue',
  'Indeedee', 'Morpeko', 'Cufant', 'Copperajah',
  'Dracozolt', 'Arctozolt', 'Dracovish', 'Arctovish',
  'Duraludon', 'Dreepy', 'Drakloak', 'Dragapult',
  'Zacian', 'Zamazenta', 'Eternatus', 'Kubfu', 'Urshifu',
  'Zarude', 'Regieleki', 'Regidrago', 'Glastrier', 'Spectrier', 'Calyrex',

  // === Gen 9 (key Pokémon) ===
  'Sprigatito', 'Floragato', 'Meowscarada',
  'Fuecoco', 'Crocalor', 'Skeledirge',
  'Quaxly', 'Quaxwell', 'Quaquaval',
  'Lechonk', 'Oinkologne', 'Tarountula', 'Spidops',
  'Nymble', 'Lokix', 'Pawmi', 'Pawmo', 'Pawmot',
  'Maschiff', 'Mabosstiff', 'Shroodle', 'Grafaiai',
  'Bramblin', 'Brambleghast', 'Klawf', 'Capsakid', 'Scovillain',
  'Farigiraf', 'Garganacl', 'Charcadet', 'Armarouge', 'Ceruledge',
  'Tadbulb', 'Bellibolt', 'Wattrel', 'Kilowattrel',
  'Manatyu', 'Revavroom', 'Cyclizar', 'Orthworm', 'Glimmet', 'Glimmora',
  'Greavard', 'Houndstone', 'Flamigo', 'Cetoddle', 'Cetitan',
  'Veluza', 'Dondozo', 'Tatsugiri', 'Annihilape', 'Clodsire',
  'Wo-Chien', 'Chien-Pao', 'Ting-Lu', 'Chi-Yu',
  'Roaring Moon', 'Iron Valiant', 'Koraidon', 'Miraidon',
  'Gouging Fire', 'Raging Bolt', 'Iron Boulder', 'Iron Crown',
  'Terapagos', 'Pecharunt',

  // === Mega / Primal / regional forms ===
  'Mega Venusaur', 'Mega Charizard X', 'Mega Charizard Y', 'Mega Blastoise',
  'Mega Beedrill', 'Mega Pidgeot', 'Mega Alakazam', 'Mega Slowbro',
  'Mega Gengar', 'Mega Kangaskhan', 'Mega Pinsir', 'Mega Gyarados',
  'Mega Aerodactyl', 'Mega Mewtwo X', 'Mega Mewtwo Y',
  'Mega Ampharos', 'Mega Scizor', 'Mega Heracross', 'Mega Houndoom',
  'Mega Tyranitar', 'Mega Sceptile', 'Mega Blaziken', 'Mega Swampert',
  'Mega Gardevoir', 'Mega Aggron', 'Mega Medicham', 'Mega Manectric',
  'Mega Banette', 'Mega Absol', 'Mega Glalie', 'Mega Salamence',
  'Mega Metagross', 'Mega Latias', 'Mega Latios', 'Mega Rayquaza',
  'Primal Kyogre', 'Primal Groudon',
  'Mega Lopunny', 'Mega Garchomp', 'Mega Lucario', 'Mega Abomasnow',
  'Mega Gallade', 'Mega Audino', 'Mega Diancie',
  'Mega Steelix', 'Mega Sableye', 'Mega Altaria', 'Mega Sharpedo',
  'Mega Camerupt', 'Mega Pidgeot',
  'Shadow Mewtwo', 'Shadow Lugia', 'Shadow Ho-Oh',
];
